apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

commonLabels:
  project: instavote
  env: staging

commonAnnotations:
  supported-by: "nawapan.a@gmail.com"

namespace: instavote
